"""empty message

Revision ID: 06a468fbb1be
Revises: 13beeda5bc99
Create Date: 2025-04-23 12:34:01.483399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06a468fbb1be'
down_revision: Union[str, None] = '13beeda5bc99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('terms', sa.JSON(), nullable=True))
    op.add_column('operations', sa.Column('result', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operations', 'result')
    op.drop_column('operations', 'terms')
    # ### end Alembic commands ###
